openapi: 3.1.0
info:
  title: OpenAPI definition
  version: 1.0.0-oas3.1
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /suppliers:
    get:
      tags:
        - supplier-controller
      operationId: listSupplier
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SupplierDTO'
    post:
      tags:
        - supplier-controller
      operationId: createSupplier
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSupplierRequest'
        required: true
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SupplierDTO'
  /offers:
    get:
      tags:
        - offer-controller
      operationId: listOffers
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OfferDTO'
    post:
      tags:
        - offer-controller
      operationId: createOffer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOfferRequest'
        required: true
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OfferDTO'
  /offers/{id}/start-work:
    post:
      tags:
        - offer-controller
      operationId: startWork
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OfferDTO'
  /offers/{id}/invoice:
    post:
      tags:
        - offer-controller
      operationId: invoiceOffer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OfferDTO'
  /offers/{id}/deliver:
    post:
      tags:
        - offer-controller
      operationId: deliverWork
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OfferDTO'
  /offers/{id}/accept-offer:
    post:
      tags:
        - offer-controller
      operationId: acceptOffer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcceptOfferRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OfferDTO'
  /offers/{id}/accept-delivery:
    post:
      tags:
        - offer-controller
      operationId: acceptDelivery
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcceptDeliveryRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OfferDTO'
  /customers:
    get:
      tags:
        - customer-controller
      operationId: listCustomers
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerDTO'
    post:
      tags:
        - customer-controller
      operationId: createCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomerRequest'
        required: true
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CustomerDTO'
  /offers/{id}:
    get:
      tags:
        - offer-controller
      operationId: getOffer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OfferDTO'
    patch:
      tags:
        - offer-controller
      operationId: updateOffer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateOfferRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OfferDTO'
  /suppliers/{id}:
    get:
      tags:
        - supplier-controller
      operationId: getSupplier
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SupplierDTO'
  /customers/{id}:
    get:
      tags:
        - customer-controller
      operationId: getCustomer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CustomerDTO'
components:
  schemas:
    CreateSupplierRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        email:
          type: string
          minLength: 1
        password:
          type: string
          minLength: 1
    SupplierDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        created_at:
          type: string
          format: date-time
    CreateOfferRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
        description:
          type: string
        price:
          type: number
        supplierId:
          type: integer
          format: int64
        customerId:
          type: integer
          format: int64
      required:
        - customerId
        - price
        - supplierId
    OfferDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        price:
          type: number
        status:
          type: string
        supplierName:
          type: string
        customerName:
          type: string
        createdAt:
          type: string
          format: date-time
    AcceptOfferRequest:
      type: object
      properties:
        accepted:
          type: boolean
    AcceptDeliveryRequest:
      type: object
      properties:
        accepted:
          type: boolean
    CreateCustomerRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        email:
          type: string
          minLength: 1
        password:
          type: string
          minLength: 1
    CustomerDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        created_at:
          type: string
          format: date-time
    UpdateOfferRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        price:
          type: number